version: "3.8"

services:
    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: neptune
          POSTGRES_USER: neptune
          POSTGRES_DB: neptune
        ports:
          - "5432:5432"
    postgres_test:
            image: postgres
            restart: always
            environment:
              POSTGRES_PASSWORD: neptune
              POSTGRES_USER: neptune
              POSTGRES_DB: neptune
            ports:
              - "5433:5432"
    redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
      environment:
        - REDIS_PASSWORD=neptune
        - REDIS_PORT=6379