name: migrations
on: push
jobs:
    migration_test:
        runs-on: ubuntu-latest
        
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: neptune
                    POSTGRES_PASSWORD: neptune
                    POSTGRES_DB: neptune
                ports:
                    - 5432:5432
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v4
            with:
              go-version: '1.21'
          # You can test your matrix by printing the current Go version
          - name: Display Go version
            run: go version
          - name: install goose
            run: go install github.com/pressly/goose/v3/cmd/goose@latest
          - name: Migrate latest version
            run: make up
          - name: Rollback first version
            run: make reset

         