name: tests
on: push
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21'
            - name: Run unit tests
              run: go test ./...