name: tests
on: push
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: '1.21'
            - name: Install deps
              run: go mod vendor
            - name: Run unit tests
              run: make test_unit